name: Deploy gallery

on:
  push:
    branches: [ main ]   # adjust if your default branch is different

permissions:
  contents: read          # needed for checkout
  pages: write            # to deploy
  id-token: write         # to authenticate the deploy

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Compress originals
        run: |
          npm install --no-save imagemin-cli imagemin-mozjpeg
          npx imagemin-cli "images/*.{jpg,jpeg}" \
            --plugin=mozjpeg \
            --out-dir=images
        
      - name: Build HTML & thumbnails
        run: |
          npm install --no-save image-size sharp
          node .github/scripts/generate.js

      - name: Prepare publish directory
        run: |
          mkdir -p public
          rsync -av --exclude='public' --exclude='.git*' --exclude='node_modules' ./ public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      # 6️⃣  Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
